version: '3.3'

# 参考
# http://sig9.hatenablog.com/entry/2019/07/07/000000
# https://tsgkdt.hatenablog.jp/entry/2019/01/03/215752
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./install-plugin.sh:/tmp/install-plugin.sh
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    networks:
      - esnet
    entrypoint: >
       bash -c "chmod +x /tmp/install-plugin.sh &&
                /tmp/install-plugin.sh analysis-kuromoji && 
                /tmp/install-plugin.sh repository-s3 && 
               docker-entrypoint.sh"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:
